sudo: required 
language: generic
services: 
    - docker

before_install:
    - docker build -t isabeDel/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true isabeDel/react-test npm test

after_success:
    - docker build -t isabeDel/multi-client ./client
    - docker build -t isabeDel/multi-nginx ./nginx
    - docker build -t isabeDel/multi-server ./server
    - docker build -t isabeDel/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push isabeDel/multi-client
    - docker push isabeDel/multi-nginx
    - docker push isabeDel/multi-server
    - docker push isabeDel/multi-worker
    
    deploy:
    provider: elasticbeanstalk
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-1-306476627547
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY